resolver: nightly-2022-06-10 # GHC 9.2.3

packages:
- .

docker:
  enable: false
  repo: psibi/alpine-haskell-stack:9.2.3v2

nix:
  # --nix on the command-line to enable.
  packages:
    - zlib
    - unzip
flags:
  stack:
    developer-mode: true

ghc-options:
   "$locals": -fhide-source-paths

extra-deps:
- git: https://github.com/psibi/process.git
  commit: df679380736c4fb77789897ec1786e1e8f3c5bae

drop-packages:
# See https://github.com/commercialhaskell/stack/pull/4712
- cabal-install
