resolver: nightly-2022-06-10 # GHC 9.2.3

packages:
- .

docker:
  enable: false
  repo: psibi/alpine-haskell-stack:9.2.3v2

nix:
  # --nix on the command-line to enable.
  packages:
    - zlib
    - unzip
flags:
  stack:
    developer-mode: true

ghc-options:
   "$locals": -fhide-source-paths

extra-deps:
- git: https://github.com/bgamari/process.git
  commit: f5e10c4a391c7f9c5347858bda1b173a56b393a7

drop-packages:
# See https://github.com/commercialhaskell/stack/pull/4712
- cabal-install
