resolver: nightly-2022-06-10 # GHC 9.2.3

packages:
- .

docker:
  enable: false
  repo: psibi/alpine-haskell-stack:9.2.3v2

nix:
  # --nix on the command-line to enable.
  packages:
    - zlib
    - unzip
flags:
  stack:
    developer-mode: true

ghc-options:
   "$locals": -fhide-source-paths

extra-deps:
- process-1.6.14.0
- Cabal-3.6.3.0@sha256:ff97c442b0c679c1c9876acd15f73ac4f602b973c45bde42b43ec28265ee48f4,12459

allow-newer: true

drop-packages:
# See https://github.com/commercialhaskell/stack/pull/4712
- cabal-install
